// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID         int64              `db:"id" json:"id"`
	Payload    []byte             `db:"payload" json:"payload"`
	Source     pgtype.Text        `db:"source" json:"source"`
	ReceivedAt pgtype.Timestamptz `db:"received_at" json:"received_at"`
}
