// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (payload, source)
VALUES ($1, $2)
`

type InsertEventParams struct {
	Payload []byte      `db:"payload" json:"payload"`
	Source  pgtype.Text `db:"source" json:"source"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent, arg.Payload, arg.Source)
	return err
}
